services:
  postgres:
    ports:
      - "55432:5432"
    volumes:
      - pgdata_test_int:/var/lib/postgresql
  backend:
    ports:
      - "8811:8080"
    environment:
      APP_AUTH_REGISTER_ENABLED: "true"

volumes:
  pgdata_test_int:
