import React, { useState, useRef, useEffect } from 'react';

export const EMOJI_SECTIONS = [
  {
    label: 'Smileys & Emotion',
    emoji: '😀',
    emojis: [
      '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','🫠','😉','😊','😇','🥰','😍','🤩','😘','😗','😚','😙','🥲','😋','😛','😜','🤪','😝','🤑','🤗','🫡','🤭','🫢','🫣','🤫','🤔','🫤','😐','😑','😶','🫥','😏','😒','🙄','😬','🤥','🫨','😌','😔','😪','🤤','😴','😷','🤒','🤕','🤢','🤮','🤧','🥵','🥶','🥴','😵','🤯','🤠','🥳','🥸','😎','🤓','🧐','😕','🫢','😟','🙁','☹️','😮','😯','😲','😳','🥺','🥹','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩','🤡','👹','👺','👻','👽','👾','🤖',
    ],
  },
  {
    label: 'People & Body',
    emoji: '👋',
    emojis: [
      '👋','🤚','🖐️','✋','🖖','🫱','🫲','🫳','🫴','🫷','🫸','👌','🤌','🤏','✌️','🤞','🫰','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','🫵','👍','👎','✊','👊','🤛','🤜','👏','🙌','🫶','👐','🤲','🤝','🙏','✍️','💅','🤳','💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🫀','🫁','🧠','🦷','🦴','👀','👁️','👅','👄','🫦','👶','🧒','👦','👧','🧑','👱','👨','🧔','👩','🧓','👴','👵','🙍','🙎','🙅','🙆','💁','🙋','🧏','🙇','🤦','🤷','👮','🕵️','💂','🥷','👷','🫅','🤴','👸','👳','👲','🧕','🤵','👰','🤰','🫃','🫄','🤱','👼','🎅','🤶','🧑‍🎄','🦸','🦹','🧙','🧝','🧛','🧟','🧌','🧞','🧜','🧚','🧑‍🦰','🧑‍🦱','🧑‍🦳','🧑‍🦲','👫','👬','👭','💏','💑','👪',
    ],
  },
  {
    label: 'Animals & Nature',
    emoji: '🐶',
    emojis: [
      '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐒','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄','🐝','🪱','🐛','🦋','🐌','🐞','🐜','🪲','🦟','🦗','🪳','🕷️','🦂','🐢','🐍','🦎','🦖','🦕','🐙','🦑','🦐','🦞','🦀','🐡','🐠','🐟','🐬','🐳','🐋','🦈','🦭','🐊','🐅','🐆','🦓','🫏','🦍','🦧','🦣','🐘','🦛','🦏','🐪','🐫','🦒','🦘','🦬','🐃','🐂','🐄','🫎','🐎','🐖','🐏','🐑','🦙','🐐','🦌','🐕','🐩','🦮','🐕‍🦺','🐈','🐈‍⬛','🪶','🐓','🦃','🦤','🦚','🦜','🦢','🕊️','🐇','🦝','🦨','🦡','🦫','🦦','🦥','🐁','🐀','🐿️','🦔','🐾','🐉','🐲','🌵','🎄','🌲','🌳','🌴','🪵','🌱','🌿','☘️','🍀','🎍','🪴','🎋','🍃','🍂','🍁','🪺','🪹','🍄','🐚','🪸','🪨','🌾','💐','🌷','🌹','🥀','🪷','🌺','🌸','🌼','🌻','🌞','🌝','🌛','🌜','🌚','🌕','🌖','🌗','🌘','🌑','🌒','🌓','🌔','🌙','🌟','⭐','🌠','🌌','☁️','⛅','🌤️','🌥️','🌦️','🌧️','⛈️','🌩️','🌨️','❄️','☃️','⛄','🌬️','💨','💧','💦','🫧','☔','☂️','🌊','🌫️',
    ],
  },
  {
    label: 'Food & Drink',
    emoji: '🍎',
    emojis: [
      '🍏','🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🫛','🥬','🥒','🌶️','🫑','🧄','🧅','🥔','🍠','🫚','🥐','🥯','🍞','🥖','🥨','🧀','🥚','🍳','🧈','🥞','🧇','🥓','🥩','🍗','🍖','🦴','🌭','🍔','🍟','🍕','🫓','🥪','🥙','🧆','🌮','🌯','🫔','🥗','🥘','🫕','🥫','🫙','🍝','🍜','🍲','🍛','🍣','🍱','🥟','🦪','🍤','🍙','🍚','🍘','🍥','🥮','🍢','🧁','🍡','🍧','🍨','🍦','🥧','🍰','🎂','🍮','🍭','🍬','🍫','🍿','🍩','🍪','🌰','🥜','🍯','🧃','🥤','🧋','🍵','☕','🫖','🍺','🍻','🥂','🍷','🫗','🥃','🍸','🍹','🧉','🍾','🧊','🥄','🍴','🍽️','🥢','🫙',
    ],
  },
  {
    label: 'Travel & Places',
    emoji: '🚗',
    emojis: [
      '🚗','🚕','🚙','🚌','🚎','🏎️','🚓','🚑','🚒','🚐','🛻','🚚','🚛','🚜','🏍️','🛵','🛺','🚲','🛴','🛹','🛼','🚏','🛣️','🛤️','⛽','🚧','⚓','🛟','⛵','🚤','🛥️','🛳️','⛴️','🚢','✈️','🛩️','🛫','🛬','🪂','💺','🚁','🚟','🚠','🚡','🛰️','🚀','🛸','🎡','🎢','🎠','🏗️','🌁','🗼','🏢','🏬','🏣','🏤','🏥','🏦','🏨','🏩','💒','🏛️','⛪','🕌','🕍','🛕','🕋','⛩️','🗾','🎑','🏞️','🌅','🌄','🌠','🎇','🎆','🌃','🏙️','🌉','🌌','🌁','🗺️','🧭','🏔️','⛰️','🌋','🗻','🏕️','🏖️','🏜️','🏝️','🏟️','🏛️','🏗️','🧱','🪨','🪵','🛖','🏘️','🏚️','🏠','🏡','🏢','🏣','🏤','🏥','🏦','🏨','🏩','🏪','🏫','🏭','🏯','🏰','💎','🗽','🗿','🗺️',
    ],
  },
  {
    label: 'Activities',
    emoji: '⚽',
    emojis: [
      '⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🪀','🏓','🏸','🏒','🥍','🏑','🥊','🥋','🎽','🛹','🛼','🛷','⛸️','🥌','🎿','⛷️','🏂','🪂','🏋️','🤼','🤸','⛹️','🤺','🏇','🧘','🏄','🏊','🤽','🚣','🧗','🚵','🚴','🏆','🥇','🥈','🥉','🏅','🎖️','🏵️','🎗️','🎫','🎟️','🎪','🤹','🎭','🎨','🎬','🎤','🎧','🎼','🎵','🎶','🎷','🪗','🎸','🎹','🎺','🎻','🪕','🥁','🪘','🎯','🎳','🎮','🎰','🧩','🪄','🎲','♟️','🎭','🖼️','🎨','🧵','🪡','🧶','🪢',
    ],
  },
  {
    label: 'Objects',
    emoji: '💡',
    emojis: [
      '💡','🔦','🕯️','🪔','🧱','💰','💴','💵','💶','💷','💸','💳','🪙','💹','📈','📉','📊','💼','🧳','📁','📂','🗂️','📋','📌','📍','📎','🖇️','📏','📐','✂️','🗃️','🗄️','🗑️','🔒','🔓','🔏','🔐','🔑','🗝️','🔨','🪓','⛏️','⚒️','🛠️','🗡️','⚔️','🔫','🛡️','🪚','🔧','🪛','🔩','⚙️','🗜️','🔗','⛓️','🪝','🧰','🧲','🪜','⚗️','🔭','🔬','🩺','🩻','💊','🩹','🩼','🩺','🪒','🧴','🧷','🧹','🧺','🧻','🪣','🧼','🫧','🪥','🧽','🧯','🛒','🚪','🪞','🪟','🛏️','🛋️','🚽','🪠','🚿','🛁','🪤','🧸','🪆','🖼️','🪞','🛍️','📱','💻','🖥️','🖨️','⌨️','🖱️','📷','📸','📹','🎥','📽️','📞','☎️','📟','📠','📺','📻','🧭','⏱️','⏲️','⏰','🕰️','⌚','📡','🔋','🪫','🔌','💡','🔦','🕯️','🔭','📡',
    ],
  },
  {
    label: 'Symbols',
    emoji: '❤️',
    emojis: [
      '❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❤️‍🔥','❤️‍🩹','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉️','✡️','🔯','🕎','☯️','☦️','🛐','⛎','♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓','🆔','⚛️','🉑','☢️','☣️','📴','📳','🈶','🈚','🈸','🈺','🈷️','✴️','🆚','💮','🉐','㊙️','㊗️','🈴','🈵','🈹','🈲','🅰️','🅱️','🆎','🆑','🅾️','🆘','❌','⭕','🛑','⛔','📛','🚫','💯','💢','♨️','🚷','🚯','🚳','🚱','🔞','📵','🔕','🔇','🔈','🔉','🔊','📢','📣','🔔','🔕','🎵','🎶','⚠️','🚸','♻️','✅','❎','🆗','🆙','🆒','🆕','🆓','🔟','🔠','🔡','🔢','🔣','🔤','🅰️','🅱️','🆎','🆑','🅾️','🆘','🚾','🩺','⚕️','♾️','🔱','📛','🔰','⭕','✔️','❌','❓','❔','❕','❗','〰️','💱','💲','➕','➖','➗','✖️','🟰','♾️','‼️','⁉️','🔅','🔆','〽️','⚜️','🔷','🔶','🔹','🔸','🔺','🔻','💠','🔘','🔳','🔲',
    ],
  },
  {
    label: 'Flags',
    emoji: '🏁',
    emojis: [
      '🏁','🚩','🎌','🏴','🏳️','🏳️‍🌈','🏳️‍⚧️','🏴‍☠️','🇦🇫','🇦🇱','🇩🇿','🇦🇩','🇦🇴','🇦🇬','🇦🇷','🇦🇲','🇦🇺','🇦🇹','🇦🇿','🇧🇸','🇧🇭','🇧🇩','🇧🇧','🇧🇾','🇧🇪','🇧🇿','🇧🇯','🇧🇹','🇧🇴','🇧🇦','🇧🇼','🇧🇷','🇧🇳','🇧🇬','🇧🇫','🇧🇮','🇨🇻','🇨🇦','🇨🇫','🇹🇩','🇨🇱','🇨🇳','🇨🇴','🇰🇲','🇨🇬','🇨🇩','🇨🇷','🇨🇮','🇭🇷','🇨🇺','🇨🇾','🇨🇿','🇩🇰','🇩🇯','🇩🇲','🇩🇴','🇪🇨','🇪🇬','🇸🇻','🇬🇶','🇪🇷','🇪🇪','🇸🇿','🇪🇹','🇫🇯','🇫🇮','🇫🇷','🇬🇦','🇬🇲','🇬🇪','🇩🇪','🇬🇭','🇬🇷','🇬🇩','🇬🇹','🇬🇳','🇬🇼','🇬🇾','🇭🇹','🇭🇳','🇭🇺','🇮🇸','🇮🇳','🇮🇩','🇮🇷','🇮🇶','🇮🇪','🇮🇱','🇮🇹','🇯🇲','🇯🇵','🇯🇴','🇰🇿','🇰🇪','🇰🇮','🇰🇼','🇰🇬','🇱🇦','🇱🇻','🇱🇧','🇱🇸','🇱🇷','🇱🇾','🇱🇮','🇱🇹','🇱🇺','🇲🇬','🇲🇼','🇲🇾','🇲🇻','🇲🇱','🇲🇹','🇲🇭','🇲🇷','🇲🇺','🇲🇽','🇫🇲','🇲🇩','🇲🇨','🇲🇳','🇲🇪','🇲🇦','🇲🇿','🇲🇲','🇳🇦','🇳🇷','🇳🇵','🇳🇱','🇳🇿','🇳🇮','🇳🇪','🇳🇬','🇰🇵','🇲🇰','🇳🇴','🇴🇲','🇵🇰','🇵🇼','🇵🇦','🇵🇬','🇵🇾','🇵🇪','🇵🇭','🇵🇱','🇵🇹','🇶🇦','🇷🇴','🇷🇺','🇷🇼','🇰🇳','🇱🇨','🇻🇨','🇼🇸','🇸🇲','🇸🇹','🇸🇦','🇸🇳','🇷🇸','🇸🇱','🇸🇬','🇸🇰','🇸🇮','🇸🇧','🇸🇴','🇿🇦','🇰🇷','🇸🇸','🇪🇸','🇱🇰','🇸🇩','🇸🇷','🇸🇪','🇨🇭','🇸🇾','🇹🇼','🇹🇯','🇹🇿','🇹🇭','🇹🇱','🇹🇬','🇹🇴','🇹🇹','🇹🇳','🇹🇷','🇹🇲','🇹🇻','🇺🇬','🇺🇦','🇦🇪','🇬🇧','🇺🇸','🇺🇾','🇺🇿','🇻🇺','🇻🇪','🇻🇳','🇾🇪','🇿🇲','🇿🇼',
    ],
  },
];

/**
 * Sparse tags per emoji for keyword search.
 * Each emoji maps to descriptive words the user might type.
 * Not every emoji has tags - unmapped ones fall back to section label search.
 */
export const EMOJI_TAGS: Record<string, string[]> = {
  // Smileys & Emotion
  '😀': ['smile', 'face', 'grin', 'happy', 'big'],
  '😃': ['smile', 'face', 'happy', 'open'],
  '😄': ['smile', 'face', 'happy', 'grin'],
  '😁': ['smile', 'face', 'happy', 'beams'],
  '😆': ['laugh', 'face', 'happy', 'satisfied'],
  '😅': ['laugh', 'face', 'sweat', 'nervous', 'happy'],
  '🤣': ['laugh', 'floor', 'rolling', 'hilarious'],
  '😂': ['laugh', 'tears', 'joy', 'funny'],
  '🙂': ['smile', 'face', 'slight', 'happy'],
  '🙃': ['upside', 'face', 'silly', 'sarcastic'],
  '🫠': ['melting', 'face', 'dying'],
  '😉': ['wink', 'face', 'flirt', 'playful'],
  '😊': ['smile', 'face', 'happy', 'blush', 'shy'],
  '😇': ['face', 'angel', 'halo', 'innocent'],
  '🥰': ['love', 'face', 'hearts', 'adore'],
  '😍': ['love', 'face', 'eyes', 'smile'],
  '🤩': ['star', 'struck', 'face', 'excited', 'wow'],
  '😘': ['kiss', 'face', 'love', 'blowing'],
  '😗': ['kiss', 'face', 'meh'],
  '😚': ['kiss', 'face', 'eyes', 'closed'],
  '😙': ['kiss', 'face', 'smile', 'eyes'],
  '🥲': ['tear', 'face', 'sad', 'holding'],
  '😋': ['tasty', 'face', 'yum', 'delicious', 'tongue'],
  '😛': ['tongue', 'face', 'silly', 'playful'],
  '😜': ['tongue', 'wink', 'face', 'silly', 'playful'],
  '🤪': ['zany', 'face', 'goofy', 'silly', 'crazy'],
  '😝': ['tongue', 'face', 'eyes', 'silly'],
  '🤑': ['money', 'face', 'rich', 'dollar'],
  '🤗': ['hugging', 'face', 'hug', 'warm'],
  '🫡': ['salute', 'face', 'respect', 'military'],
  '🤭': ['hand', 'mouth', 'face', 'oops', 'shy'],
  '🫢': ['hand', 'mouth', 'face', 'gasp', 'shocked'],
  '🫣': ['seeing', 'face', 'hands', 'peek', 'embarrassed'],
  '🤫': ['shush', 'face', 'quiet', 'silence'],
  '🤔': ['thinking', 'face', 'hmm', 'think', 'ponder'],
  '🫤': ['face', 'unimpressed', 'skeptical', 'meh'],
  '😐': ['neutral', 'face', 'expressionless', 'meh'],
  '😑': ['face', 'expressionless', 'meh'],
  '😶': ['face', 'speechless', 'silent', 'mouth'],
  '🫥': ['face', 'blending', 'invisible', 'anxious'],
  '😏': ['smirk', 'face', 'smile', 'flirty'],
  '😒': ['face', 'unhappy', 'meh', 'disappointed'],
  '🙄': ['eyes', 'roll', 'face', 'annoyed', 'sarcastic'],
  '😬': ['face', 'grimace', 'awkward', 'nervous'],
  '🤥': ['lying', 'face', 'pinocchio', 'tall'],
  '🫨': ['face', 'shocked', 'shaking', 'scared'],
  '😌': ['face', 'relieved', 'calm', 'peaceful'],
  '😔': ['face', 'sad', 'pens', 'downcast'],
  '😪': ['face', 'sleepy', 'tired', 'yawn'],
  '🤤': ['face', 'drooling', 'hungry', 'saliva'],
  '😴': ['face', 'sleeping', 'tired', 'zzz'],
  '😷': ['mask', 'face', 'sick', 'ill', 'cold'],
  '🤒': ['thermometer', 'face', 'sick', 'fever'],
  '🤕': ['head', 'bandage', 'face', 'hurt', 'injury'],
  '🤢': ['nauseated', 'face', 'sick', 'vomit'],
  '🤮': ['face', 'vomiting', 'sick', 'puke'],
  '🤧': ['face', 'sneezing', 'sick', 'cold', 'allergy'],
  '🥵': ['hot', 'face', 'heat', 'fever', 'burning'],
  '🥶': ['cold', 'face', 'freezing', 'frozen'],
  '🥴': ['face', 'intoxicated', 'drunk', 'wavy', 'sick'],
  '😵': ['face', 'dizzy', 'dead', 'x eyes'],
  '🤯': ['mind', 'blown', 'face', 'shocked', 'wow'],
  '🤠': ['cowboy', 'face', 'hat', 'western'],
  '🥳': ['party', 'face', 'celebration', 'birthday', 'hat'],
  '🥸': ['face', 'disguised', 'clown', 'nose'],
  '😎': ['sunglasses', 'face', 'cool'],
  '🤓': ['nerd', 'face', 'geek', 'glasses'],
  '🧐': ['monocle', 'face', 'classy', 'sophisticated'],
  '😕': ['face', 'confused', 'uncertain', 'worried'],
  '😟': ['worried', 'face', 'nervous', 'concerned'],
  '🙁': ['frown', 'face', 'unhappy', 'sad'],
  '☹️': ['frown', 'face', 'sad', 'unhappy'],
  '😮': ['face', 'surprised', 'shocked', 'open mouth'],
  '😯': ['face', 'hushed', 'surprised'],
  '😲': ['face', 'astonished', 'shocked', 'amazed'],
  '😳': ['flushed', 'face', 'embarrassed', 'blush'],
  '🥺': ['pleading', 'face', 'puppy', 'begging', 'cute'],
  '🥹': ['face', 'holding', 'tears', 'grateful', 'proud'],
  '😦': ['face', 'frown', 'mouth', 'surprised'],
  '😧': ['face', 'anguished', 'worried', 'pain'],
  '😨': ['face', 'fearful', 'scared', 'afraid'],
  '😰': ['face', 'sweat', 'nervous', 'cold', 'anxious'],
  '😥': ['face', 'nervous', 'disappointed', 'relieved'],
  '😢': ['crying', 'face', 'sad', 'tear'],
  '😭': ['crying', 'face', 'sad', 'sob', 'tears', 'loudly'],
  '😱': ['face', 'screaming', 'fear', 'scared', 'shocked'],
  '😖': ['face', 'confounded', 'frustrated', 'upset'],
  '😣': ['face', 'struggling', 'persevering', 'troubled'],
  '😞': ['disappointed', 'face', 'sad', 'dejected'],
  '😓': ['face', 'sweat', 'disappointed', 'hot'],
  '😩': ['face', 'weary', 'tired', 'frustrated'],
  '😫': ['face', 'tired', 'weary', 'frustrated'],
  '🥱': ['face', 'yawning', 'bored', 'tired'],
  '😤': ['face', 'triumph', 'frustrated', 'determined'],
  '😡': ['angry', 'face', 'mad', 'pouting'],
  '😠': ['angry', 'face', 'mad'],
  '🤬': ['face', 'symbols', 'angry', 'foul', 'cursing'],
  '😈': ['smile', 'face', 'horns', 'devil', 'evil'],
  '👿': ['angry', 'face', 'horns', 'devil', 'evil'],
  '💀': ['skull', 'dead', 'death'],
  '☠️': ['skull', 'bones', 'danger', 'poison'],
  '💩': ['poop', 'shit', 'poo', 'crap'],
  '🤡': ['clown', 'face', 'fool'],
  '👹': ['ogre', 'monster', 'creature'],
  '👺': ['goblin', 'monster', 'creature'],
  '👻': ['ghost', 'boo', 'spooky', 'haunted'],
  '👽': ['alien', 'ufo', 'space', 'creature'],
  '👾': ['alien', 'monster', 'game', 'retro'],
  '🤖': ['robot', 'face', 'android', 'machine'],
  // People & Body
  '👋': ['wave', 'hand', 'hello', 'bye', 'greeting'],
  '🤚': ['hand', 'raised', 'back', 'palm'],
  '🖐️': ['hand', 'raised', 'fingers', 'spread'],
  '✋': ['hand', 'raised', 'palm', 'stop'],
  '🖖': ['vulcan', 'hand', 'spock', 'star trek'],
  '🫱': ['hand', 'right', 'pointing'],
  '🫲': ['hand', 'left', 'pointing'],
  '🫳': ['hand', 'palm', 'down'],
  '🫴': ['hand', 'palm', 'up'],
  '🫷': ['hand', 'pushing', 'left'],
  '🫸': ['hand', 'pushing', 'right'],
  '👌': ['ok', 'hand', 'perfect', 'good'],
  '🤌': ['hand', 'fingers', 'together', 'italian'],
  '🤏': ['hand', 'pinch', 'small', 'tiny'],
  '✌️': ['victory', 'hand', 'peace', 'two'],
  '🤞': ['fingers', 'crossed', 'lucky', 'hope'],
  '🫰': ['finger', 'heart', 'hand', 'love'],
  '🤟': ['hand', 'love', 'youth', 'ily'],
  '🤘': ['hand', 'horns', 'rock', 'metal'],
  '🤙': ['hand', 'call', 'hawaii', 'call me'],
  '👈': ['hand', 'pointing', 'left', 'backhand'],
  '👉': ['hand', 'pointing', 'right', 'backhand'],
  '👆': ['hand', 'pointing', 'up', 'backhand'],
  '🖕': ['hand', 'middle', 'finger', 'rude', 'offensive'],
  '👇': ['hand', 'pointing', 'down', 'backhand'],
  '☝️': ['hand', 'pointing', 'up', 'finger'],
  '🫵': ['hand', 'pointing', 'you', 'finger'],
  '👍': ['thumb', 'up', 'yes', 'good', 'agree'],
  '👎': ['thumb', 'down', 'no', 'bad', 'disagree'],
  '✊': ['hand', 'fist', 'raised', 'power'],
  '👊': ['hand', 'fist', 'oncoming', 'punch'],
  '🤛': ['fist', 'left', 'hand'],
  '🤜': ['fist', 'right', 'hand'],
  '👏': ['clapping', 'hands', 'applause', 'praise'],
  '🙌': ['hands', 'raised', 'celebration', 'praise'],
  '🫶': ['hands', 'heart', 'love', 'care'],
  '👐': ['hands', 'open', 'welcome'],
  '🤲': ['hands', 'palms', 'up', 'prayer'],
  '🤝': ['handshake', 'agreement', 'deal'],
  '🙏': ['hands', 'together', 'pray', 'please', 'thanks'],
  '✍️': ['writing', 'hand', 'write'],
  '💅': ['nail', 'polish', 'beauty', 'cosmetics'],
  '🤳': ['selfie', 'camera', 'phone', 'picture'],
  '💪': ['muscle', 'bicep', 'strong', 'flex'],
  '🦾': ['mechanical', 'arm', 'robot', 'prosthetic'],
  '🦿': ['mechanical', 'leg', 'robot', 'prosthetic'],
  '🦵': ['leg', 'body'],
  '🦶': ['foot', 'body', 'kick'],
  '👂': ['ear', 'body', 'listen', 'hear'],
  '🦻': ['ear', 'hearing', 'aid', 'device'],
  '👃': ['nose', 'body', 'smell'],
  '🫀': ['heart', 'anatomical', 'organ', 'medical'],
  '🫁': ['lungs', 'anatomical', 'organ', 'breath'],
  '🧠': ['brain', 'mind', 'smart', 'think'],
  '🦷': ['tooth', 'dentist', 'dental'],
  '🦴': ['bone', 'skeleton'],
  '👀': ['eyes', 'look', 'see', 'watch'],
  '👁️': ['eye', 'body', 'watch', 'see'],
  '👅': ['tongue', 'taste', 'lick'],
  '👄': ['mouth', 'lips', 'kiss'],
  '🫦': ['biting', 'lip', 'nervous', 'flirty'],
  '👶': ['baby', 'infant', 'toddler', 'newborn'],
  '🧒': ['child', 'person', 'young'],
  '👦': ['boy', 'child', 'young'],
  '👧': ['girl', 'child', 'young'],
  '🧑': ['person', 'adult', 'human'],
  '👱': ['person', 'blonde', 'hair'],
  '👨': ['man', 'male', 'adult'],
  '🧔': ['man', 'beard', 'facial', 'hair'],
  '👩': ['woman', 'female', 'adult'],
  '🧓': ['person', 'older', 'elderly'],
  '👴': ['man', 'old', 'elderly', 'grandpa'],
  '👵': ['woman', 'old', 'elderly', 'grandma'],
  '🙍': ['person', 'frowning', 'unsure'],
  '🙎': ['person', 'pouting', 'unhappy'],
  '🙅': ['person', 'gesturing', 'no', 'not'],
  '🙆': ['person', 'gesturing', 'ok'],
  '💁': ['person', 'tipping', 'hand', 'information', 'help'],
  '🙋': ['person', 'raising', 'hand'],
  '🧏': ['person', 'deaf', 'ear'],
  '🙇': ['person', 'bowing', 'respect', 'sorry'],
  '🤦': ['person', 'facepalm', 'disbelief', 'frustrated'],
  '🤷': ['person', 'shrug', 'dunno', 'whatever'],
  '👮': ['police', 'officer', 'cop', 'law'],
  '🕵️': ['detective', 'spy', 'investigate'],
  '💂': ['guard', 'military', 'watch'],
  '🥷': ['ninja', 'stealth', 'hidden', 'warrior'],
  '👷': ['worker', 'construction', 'builder', 'helmet'],
  '🫅': ['person', 'crown', 'king', 'queen', 'royalty'],
  '🤴': ['prince', 'man', 'crown', 'royalty'],
  '👸': ['princess', 'woman', 'crown', 'royalty'],
  '👳': ['person', 'turban', 'head'],
  '👲': ['man', 'cap', 'head', 'chinese'],
  '🧕': ['woman', 'headscarf', 'hijab'],
  '🤵': ['man', 'tuxedo', 'formal', 'suit'],
  '👰': ['bride', 'woman', 'veil', 'wedding'],
  '🤰': ['pregnant', 'woman', 'baby', 'expecting'],
  '🫃': ['pregnant', 'man', 'baby', 'expecting'],
  '🫄': ['pregnant', 'person', 'baby', 'expecting'],
  '🤱': ['breast', 'feeding', 'nursing', 'baby', 'mother'],
  '👼': ['baby', 'angel', 'wings', 'heaven'],
  '🎅': ['santa', 'claus', 'xmas', 'christmas', 'father'],
  '🤶': ['mrs', 'claus', 'xmas', 'christmas', 'santa'],
  '🧑‍🎄': ['mrs', 'claus', 'xmas', 'christmas', 'santa'],
  '🦸': ['superhero', 'cape', 'power', 'hero'],
  '🦹': ['super', 'villain', 'evil', 'cape', 'bad'],
  '🧙': ['mage', 'witch', 'wizard', 'sorcerer', 'magic'],
  '🧝': ['elf', 'magic', 'fantasy', 'forest'],
  '🧛': ['vampire', 'dracula', 'blood', 'fangs'],
  '🧟': ['zombie', 'dead', 'undead', 'walker'],
  '🧌': ['troll', 'monster', 'fantasy', 'bridge'],
  '🧞': ['genie', 'lamp', 'wish', 'magic'],
  '🧜': ['merperson', 'mermaid', 'sea', 'water'],
  '🧚': ['fairy', 'wings', 'magic'],
  '👫': ['man', 'woman', 'boy', 'hands', 'couple'],
  '👬': ['man', 'men', 'hands', 'couple', 'gay'],
  '👭': ['woman', 'women', 'hands', 'couple', 'lesbian'],
  '💏': ['kissing', 'couple', 'love'],
  '💑': ['couple', 'heart', 'love'],
  '👪': ['family', 'parents', 'children', 'kids'],
  // Animals
  '🐶': ['dog', 'pet', 'puppy', 'woof'],
  '🐱': ['cat', 'pet', 'kitty', 'meow'],
  '🐭': ['mouse', 'pet', 'rodent', 'squeak'],
  '🐹': ['hamster', 'pet', 'rodent', 'small'],
  '🐰': ['rabbit', 'pet', 'bunny', 'hop', 'ears'],
  '🦊': ['fox', 'cunning', 'tricky', 'red'],
  '🐻': ['bear', 'animal', 'wild', 'cub'],
  '🐼': ['panda', 'bamboo', 'cute', 'peaceful'],
  '🐻‍❄️': ['polar', 'bear', 'cold', 'snow'],
  '🐨': ['koala', 'australia', 'eucalyptus'],
  '🐯': ['tiger', 'cat', 'wild', 'stripe'],
  '🦁': ['lion', 'king', 'jungle', 'mane', 'cat'],
  '🐮': ['cow', 'animal', 'moo', 'bovine'],
  '🐷': ['pig', 'animal', 'oink', 'hog'],
  '🐸': ['frog', 'toad', 'green', 'croak'],
  '🐵': ['monkey', 'face', 'banana', 'chimp'],
  '🙈': ['monkey', 'see', 'evil', 'eyes'],
  '🙉': ['monkey', 'hear', 'evil', 'ears'],
  '🙊': ['monkey', 'speak', 'evil', 'mouth'],
  '🐒': ['monkey', 'chimp', 'animal'],
  '🐔': ['chicken', 'hen', 'bird', 'cluck'],
  '🐧': ['penguin', 'bird', 'cold', 'antarctica'],
  '🐦': ['bird', 'blue', 'small', 'chirp'],
  '🐤': ['baby', 'chick', 'chicken', 'hatched'],
  '🦆': ['duck', 'mallard', 'quack'],
  '🦅': ['eagle', 'bird', 'flying', 'strong'],
  '🦉': ['owl', 'bird', 'hoot', 'wise', 'nocturnal'],
  '🦇': ['bat', 'flying', 'dark', 'cave'],
  '🐺': ['wolf', 'howl', 'forest', 'pack'],
  '🐗': ['boar', 'pig', 'wild'],
  '🐴': ['horse', 'animal', 'equine', 'neigh'],
  '🦄': ['unicorn', 'magic', 'fantasy', 'horn'],
  '🐝': ['bee', 'honey', 'insect', 'buzz'],
  '🪱': ['worm', 'insect', 'dirt'],
  '🐛': ['bug', 'caterpillar', 'insect'],
  '🦋': ['butterfly', 'moth', 'pretty', 'colorful'],
  '🐌': ['snail', 'slow', 'shell', 'slug'],
  '🐞': ['ladybug', 'beetle', 'bug', 'ladybird'],
  '🐜': ['ant', 'bug', 'insect', 'colony'],
  '🪲': ['beetle', 'bug', 'insect'],
  '🦟': ['mosquito', 'insect', 'fly', 'bite'],
  '🦗': ['cricket', 'insect', 'chirp'],
  '🪳': ['cockroach', 'insect', 'bug', 'pest'],
  '🕷️': ['spider', 'web', 'bug', 'arachnid'],
  '🦂': ['scorpion', 'stinger', 'desert', 'venom'],
  '🐢': ['turtle', 'slow', 'shell', 'tortoise'],
  '🐍': ['snake', 'serpent', 'hiss', 'reptile'],
  '🦎': ['lizard', 'reptile', 'cold', 'tail'],
  '🦖': ['dinosaur', 'rex', 'extinct', 'big'],
  '🦕': ['dinosaur', 'brontosaurus', 'long', 'neck'],
  '🐙': ['octopus', 'sea', 'tentacles', 'squid'],
  '🦑': ['squid', 'calamari', 'sea', 'tentacles'],
  '🦐': ['shrimp', 'sea', 'prawn', 'seafood'],
  '🦞': ['lobster', 'sea', 'crayfish', 'shell'],
  '🦀': ['crab', 'sea', 'shell', 'pincers'],
  '🐡': ['blowfish', 'fish', 'puffer', 'sea'],
  '🐠': ['fish', 'tropical', 'sea', 'reef'],
  '🐟': ['fish', 'sea', 'aquatic'],
  '🐬': ['dolphin', 'flipper', 'sea', 'smart'],
  '🐳': ['spouting', 'whale', 'sea', 'big'],
  '🐋': ['whale', 'big', 'sea', 'blue'],
  '🦈': ['shark', 'fish', 'tooth', 'ocean'],
  '🦭': ['seal', 'pup', 'sea', 'water'],
  '🐊': ['crocodile', 'reptile', 'alligator', 'swamp'],
  '🐅': ['tiger', 'jungle', 'striped', 'cat'],
  '🐆': ['leopard', 'cat', 'spotted', 'jungle'],
  '🦓': ['zebra', 'striped', 'horse', 'african'],
  '🫏': ['donkey', 'mule', 'animal'],
  '🦍': ['gorilla', 'ape', 'strong'],
  '🦧': ['orangutan', 'ape', 'monkey'],
  '🦣': ['mammoth', 'elephant', 'extinct'],
  '🐘': ['elephant', 'trunk', 'big', 'african'],
  '🦛': ['hippo', 'hippopotamus', 'big', 'river'],
  '🦏': ['rhino', 'rhinoceros', 'horn', 'big'],
  '🐪': ['camel', 'dromedary', 'hump', 'desert'],
  '🐫': ['camel', 'bactrian', 'hump', 'desert'],
  '🦒': ['giraffe', 'neck', 'long', 'spotted'],
  '🦘': ['kangaroo', 'joey', 'australia', 'hop'],
  '🦬': ['bison', 'buffalo', 'cow', 'big'],
  '🐃': ['water', 'buffalo', 'cow', 'asian'],
  '🐂': ['ox', 'bull', 'cow'],
  '🐄': ['cow', 'face', 'moo'],
  '🫎': ['moose', 'antler', 'big', 'forest'],
  '🐎': ['horse', 'face', 'race', 'equine'],
  '🐖': ['pig', 'face', 'oink', 'swine'],
  '🐏': ['ram', 'sheep', 'curled', 'horn'],
  '🐑': ['sheep', 'wool', 'lamb'],
  '🦙': ['llama', 'alpaca', 'south', 'american'],
  '🐐': ['goat', 'horn', 'animal'],
  '🦌': ['deer', 'reindeer', 'forest', 'antlers'],
  '🐕': ['dog', 'face', 'puppy', 'woof'],
  '🐩': ['poodle', 'dog', 'curly', 'pet'],
  '🦮': ['guide', 'dog', 'blind', 'seeing', 'help'],
  '🐕‍🦺': ['service', 'dog', 'medical', 'help'],
  '🐈': ['cat', 'face', 'kitty', 'meow'],
  '🐈‍⬛': ['cat', 'black', 'lucky'],
  '🪶': ['feather', 'bird', 'light'],
  '🐓': ['rooster', 'chicken', 'cockerel'],
  '🦃': ['turkey', 'bird', 'thanksgiving'],
  '🦤': ['dodo', 'extinct', 'bird'],
  '🦚': ['peacock', 'peahen', 'colorful', 'feather', 'beautiful'],
  '🦜': ['parrot', 'bird', 'talk', 'tropical', 'colorful'],
  '🦢': ['swan', 'bird', 'elegant', 'graceful'],
  '🕊️': ['dove', 'peace', 'bird', 'fly'],
  '🐇': ['rabbit', 'face', 'bunny', 'hop'],
  '🦝': ['raccoon', 'trash', 'mask', 'thief'],
  '🦨': ['skunk', 'stink', 'smelly'],
  '🦡': ['badger', 'honey', 'animal'],
  '🦫': ['beaver', 'dam', 'tail', 'wood'],
  '🦦': ['otter', 'playful', 'water', 'sea'],
  '🦥': ['sloth', 'slow', 'lazy', 'tree'],
  '🐁': ['mouse', 'face', 'rodent'],
  '🐀': ['rat', 'mouse', 'rodent'],
  '🐿️': ['chipmunk', 'mouse', 'rodent', 'cheek'],
  '🦔': ['hedgehog', 'spike', 'prickle'],
  '🐾': ['paw', 'prints', 'animal', 'tracks'],
  '🐉': ['dragon', 'face', 'mythical', 'chinese'],
  '🐲': ['dragon', 'face', 'chinese', 'mythical'],
  // Nature
  '🌵': ['cactus', 'desert', 'spiky', 'dry'],
  '🎄': ['christmas', 'tree', 'pine', 'holly', 'xmas'],
  '🌲': ['tree', 'evergreen', 'pine', 'forest'],
  '🌳': ['tree', 'deciduous', 'leafy', 'forest'],
  '🌴': ['palm', 'tree', 'tropical', 'beach'],
  '🪵': ['wood', 'log', 'firewood'],
  '🌱': ['seedling', 'sprout', 'plant', 'new'],
  '🌿': ['herb', 'leaf', 'green', 'medicine'],
  '☘️': ['leaf', 'clover', 'irish', 'st patrick'],
  '🍀': ['clover', 'four', 'leaf', 'lucky'],
  '🎍': ['bamboo', 'plant', 'chinese', 'new year'],
  '🪴': ['plant', 'potted', 'house'],
  '🎋': ['plant', 'dwarf', 'bonsai'],
  '🍃': ['leaf', 'fluttering', 'wind', 'green'],
  '🍂': ['leaf', 'falling', 'autumn', 'fall'],
  '🍁': ['maple', 'leaf', 'fall', 'canada', 'autumn'],
  '🪺': ['nest', 'bird', 'eggs'],
  '🪹': ['nest', 'empty', 'bird'],
  '🍄': ['mushroom', 'toadstool', 'fungi', 'fungal'],
  '🐚': ['shell', 'spiral', 'sea', 'beach'],
  '🪸': ['coral', 'reef', 'ocean', 'sea'],
  '🪨': ['rock', 'stone', 'boulder'],
  '🌾': ['rice', 'sheaf', 'wheat', 'grain'],
  // Flowers
  '💐': ['bouquet', 'flower', 'gift'],
  '🌷': ['tulip', 'flower', 'red', 'spring'],
  '🌹': ['rose', 'flower', 'red', 'love'],
  '🥀': ['flower', 'wilted', 'dead', 'dying'],
  '🪷': ['lotus', 'flower', 'hindu', 'buddhism'],
  '🌺': ['hibiscus', 'flower', 'tropical'],
  '🌸': ['cherry', 'blossom', 'flower', 'spring'],
  '🌼': ['blossom', 'flower', 'bloom'],
  '🌻': ['sunflower', 'flower', 'yellow', 'summer'],
  // Weather
  '🌞': ['sun', 'face', 'summer', 'hot', 'bright'],
  '🌝': ['moon', 'face', 'full', 'bright'],
  '🌛': ['moon', 'face', 'left', 'quarter'],
  '🌜': ['moon', 'face', 'right', 'quarter'],
  '🌚': ['moon', 'face', 'new', 'black'],
  '🌕': ['moon', 'full', 'bright'],
  '🌖': ['moon', 'gibbous', 'waning', 'waxing'],
  '🌗': ['moon', 'crescent', 'quarter'],
  '🌘': ['moon', 'crescent', 'waning', 'waxing'],
  '🌑': ['moon', 'new', 'black', 'dark'],
  '🌒': ['moon', 'crescent', 'waxing'],
  '🌓': ['moon', 'quarter', 'waxing'],
  '🌔': ['moon', 'gibbous', 'waxing'],
  '🌙': ['moon', 'crescent', 'night'],
  '🌟': ['glowing', 'star', 'sparkle'],
  '⭐': ['star', 'yellow', 'bright', 'shining'],
  '🌠': ['shooting', 'star', 'wish', 'meteor'],
  '🌌': ['milky', 'way', 'galaxy', 'space'],
  '☁️': ['cloud', 'weather', 'sky'],
  '⛅': ['sun', 'cloud', 'weather', 'partly'],
  '🌤️': ['sun', 'small', 'cloud'],
  '🌥️': ['cloud', 'sun', 'behind', 'cloudy'],
  '🌦️': ['sun', 'rain', 'cloud'],
  '🌧️': ['cloud', 'rain', 'drop', 'storm'],
  '⛈️': ['cloud', 'lightning', 'rain', 'thunder'],
  '🌩️': ['cloud', 'lightning', 'thunder'],
  '🌨️': ['cloud', 'snow', 'cold'],
  '❄️': ['snowflake', 'cold', 'winter', 'frosty'],
  '☃️': ['snowman', 'winter', 'cold', 'snow'],
  '⛄': ['snowman', 'winter', 'cold', 'snow', 'no snow'],
  '🌬️': ['wind', 'blowing', 'face', 'air'],
  '💨': ['dashing', 'away', 'wind', 'fast', 'speed'],
  '💧': ['droplet', 'water', 'sweat', 'tear'],
  '💦': ['splashing', 'sweat', 'water', 'droplets'],
  '🫧': ['bubbles', 'soap', 'float'],
  '☔': ['umbrella', 'rain', 'weather', 'wet'],
  '☂️': ['umbrella', 'weather'],
  '🌊': ['wave', 'water', 'sea', 'ocean'],
  '🌫️': ['fog', 'mist', 'cloudy'],
  // Food & Drink
  '🍏': ['apple', 'green', 'fruit'],
  '🍎': ['apple', 'red', 'fruit'],
  '🍐': ['pear', 'fruit'],
  '🍊': ['orange', 'fruit', 'citrus'],
  '🍋': ['lemon', 'fruit', 'citrus', 'sour'],
  '🍌': ['banana', 'fruit', 'yellow', 'monkey'],
  '🍉': ['watermelon', 'fruit', 'summer', 'red'],
  '🍇': ['grapes', 'fruit', 'purple', 'wine'],
  '🍓': ['strawberry', 'fruit', 'red', 'berry'],
  '🫐': ['blueberries', 'berry', 'fruit', 'blue'],
  '🍈': ['melon', 'fruit', 'tropical'],
  '🍒': ['cherries', 'fruit', 'red', 'sweet'],
  '🍑': ['peach', 'fruit', 'orange', 'butt'],
  '🥭': ['mango', 'fruit', 'tropical', 'exotic'],
  '🍍': ['pineapple', 'fruit', 'tropical', 'yellow'],
  '🥥': ['coconut', 'palm', 'tropical', 'water'],
  '🥝': ['kiwi', 'fruit', 'green', 'tropical'],
  '🍅': ['tomato', 'vegetable', 'red', 'salad'],
  '🍆': ['aubergine', 'eggplant', 'purple'],
  '🥑': ['avocado', 'fruit', 'green', 'guacamole', 'healthy'],
  '🥦': ['broccoli', 'vegetable', 'green', 'healthy'],
  '🫛': ['beanpod', 'beans', 'vegetable'],
  '🥬': ['leafy', 'green', 'vegetable', 'salad'],
  '🥒': ['cucumber', 'vegetable', 'pickle', 'green'],
  '🌶️': ['hot', 'pepper', 'spicy', 'chili'],
  '🫑': ['bell', 'pepper', 'vegetable', 'capsicum'],
  '🧄': ['garlic', 'spice', 'food', 'flavor'],
  '🧅': ['onion', 'spice', 'food', 'flavor'],
  '🥔': ['potato', 'vegetable', 'spud'],
  '🍠': ['sweet', 'potato', 'vegetable'],
  '🫚': ['ginger', 'root', 'spice', 'food'],
  '🥐': ['croissant', 'bread', 'french', 'pastry'],
  '🥯': ['bagel', 'bread', 'breakfast', 'baker'],
  '🍞': ['bread', 'loaf', 'toast', 'bakery'],
  '🥖': ['baguette', 'bread', 'french'],
  '🥨': ['pretzel', 'twisted', 'snack', 'german'],
  '🧀': ['cheese', 'wedge', 'food', 'dairy'],
  '🥚': ['egg', 'food', 'breakfast', 'chicken'],
  '🍳': ['cooking', 'frying', 'pan', 'breakfast'],
  '🧈': ['butter', 'dairy', 'spread'],
  '🥞': ['pancakes', 'hotcake', 'breakfast', 'food'],
  '🧇': ['waffle', 'food', 'breakfast'],
  '🥓': ['bacon', 'meat', 'pork', 'breakfast'],
  '🥩': ['meat', 'chop', 'steak'],
  '🍗': ['chicken', 'drumstick', 'meat', 'food'],
  '🍖': ['bone', 'meat', 'rib'],
  '🌭': ['hotdog', 'hot', 'dog', 'sausage', 'food'],
  '🍔': ['burger', 'hamburger', 'beef', 'fast food'],
  '🍟': ['fries', 'french', 'potato', 'fast food'],
  '🍕': ['pizza', 'cheese', 'food', 'italian'],
  '🫓': ['flatbread', 'bread', 'naan', 'pita'],
  '🥪': ['sandwich', 'bread', 'lunch', 'food'],
  '🥙': ['wrap', 'falafel', 'pita', 'food'],
  '🧆': ['falafel', 'chickpea', 'food', 'middle eastern'],
  '🌮': ['taco', 'mexican', 'food', 'corn'],
  '🌯': ['burrito', 'mexican', 'wrap', 'food'],
  '🫔': ['tamale', 'mexican', 'food', 'corn'],
  '🥗': ['salad', 'bowl', 'healthy', 'green'],
  '🥘': ['pan', 'stew', 'food', 'shallow'],
  '🫕': ['fondue', 'cheese', 'swiss', 'pot'],
  '🥫': ['can', 'canned', 'food', 'tin'],
  '🫙': ['jar', 'container', 'pickle'],
  '🍝': ['pasta', 'spaghetti', 'food', 'italian'],
  '🍜': ['bowl', 'ramen', 'steaming', 'noodle'],
  '🍲': ['pot', 'stew', 'food', 'soup'],
  '🍛': ['curry', 'rice', 'indian', 'spicy'],
  '🍣': ['sushi', 'japanese', 'fish', 'rice'],
  '🍱': ['bento', 'box', 'japanese', 'lunch'],
  '🥟': ['dumpling', 'empanada', 'japanese', 'food'],
  '🦪': ['oyster', 'seafood', 'clam'],
  '🍤': ['fried', 'shrimp', 'prawn', 'tempura'],
  '🍙': ['rice', 'ball', 'japanese', 'food'],
  '🍚': ['rice', 'cooked', 'steamed', 'bowl'],
  '🍘': ['rice', 'cracker', 'japanese', 'food'],
  '🍥': ['fish', 'cake', 'sushi', 'swirl'],
  '🥮': ['moon', 'cake', 'dessert', 'food'],
  '🍢': ['oden', 'japanese', 'skewer', 'food'],
  '🧁': ['cupcake', 'dessert', 'sweet', 'cake'],
  '🍡': ['dango', 'japanese', 'sweet', 'skewer'],
  '🍧': ['shaved', 'ice', 'dessert', 'sweet'],
  '🍨': ['ice', 'cream', 'dessert', 'cold'],
  '🍦': ['soft', 'serve', 'ice', 'dessert'],
  '🥧': ['pie', 'dessert', 'food', 'pastry'],
  '🍰': ['shortcake', 'cake', 'dessert', 'sweet'],
  '🎂': ['cake', 'birthday', 'celebration', 'candle'],
  '🍮': ['custard', 'dessert', 'pudding'],
  '🍭': ['lollipop', 'candy', 'sweet'],
  '🍬': ['candy', 'sweet', 'sugar'],
  '🍫': ['chocolate', 'bar', 'sweet', 'candy'],
  '🍿': ['popcorn', 'movie', 'snack'],
  '🍩': ['donut', 'doughnut', 'sweet', 'pastry'],
  '🍪': ['cookie', 'sweet', 'biscuit'],
  '🌰': ['chestnut', 'food', 'brown'],
  '🥜': ['peanuts', 'nut', 'snack'],
  '🍯': ['honey', 'pot', 'sweet', 'bee'],
  '🧃': ['juice', 'box', 'drink', 'beverage'],
  '🥤': ['cup', 'straw', 'soda', 'drink'],
  '🧋': ['bubble', 'tea', 'boba', 'drink', 'taiwan'],
  '🍵': ['tea', 'cup', 'beverage', 'hot', 'green'],
  '☕': ['hot', 'beverage', 'coffee', 'steaming'],
  '🫖': ['teapot', 'tea', 'hot', 'brew'],
  '🍺': ['beer', 'mug', 'drink', 'drinking'],
  '🍻': ['beer', 'clinking', 'mugs', 'cheers', 'drink'],
  '🥂': ['glasses', 'clinking', 'cheers', 'celebration'],
  '🍷': ['wine', 'glass', 'drink'],
  '🫗': ['pouring', 'liquid', 'water', 'glass'],
  '🥃': ['tumbler', 'whisky', 'drink', 'shot', 'alcohol'],
  '🍸': ['cocktail', 'drink', 'martini', 'party'],
  '🍹': ['tropical', 'drink', 'cocktail', 'mojito'],
  '🧉': ['mate', 'tea', 'drink', 'argentina'],
  '🍾': ['champagne', 'bottle', 'cork', 'celebration'],
  '🧊': ['ice', 'cube', 'cold', 'frozen'],
  '🥄': ['spoon', 'cutlery', 'utensil'],
  '🍴': ['fork', 'knife', 'plate', 'cutlery'],
  '🍽️': ['fork', 'knife', 'plate', 'dining', 'cutlery'],
  '🥢': ['chopsticks', 'asian', 'utensil'],
  // Travel & Places
  '🚗': ['car', 'auto', 'vehicle', 'drive'],
  '🚕': ['taxi', 'cab', 'vehicle', 'ride'],
  '🚙': ['car', 'suv', 'vehicle', 'drive'],
  '🚌': ['bus', 'vehicle', 'transport', 'public'],
  '🚎': ['tram', 'vehicle', 'transport'],
  '🏎️': ['racing', 'car', 'fast', 'formula'],
  '🚓': ['police', 'car', 'vehicle'],
  '🚑': ['ambulance', 'medical', 'vehicle'],
  '🚒': ['fire', 'engine', 'truck', 'vehicle'],
  '🚐': ['minibus', 'vehicle', 'transport'],
  '🛻': ['pick', 'truck', 'vehicle'],
  '🚚': ['truck', 'delivery', 'vehicle'],
  '🚛': ['truck', 'articulated', 'lorry', 'vehicle'],
  '🚜': ['tractor', 'farm', 'vehicle'],
  '🏍️': ['motorcycle', 'racing', 'fast', 'bike'],
  '🛵': ['motor', 'scooter', 'vehicle'],
  '🛺': ['auto', 'rickshaw', 'tuk', 'vehicle'],
  '🚲': ['bicycle', 'bike', 'cycle', 'ride'],
  '🛴': ['scooter', 'kick', 'ride'],
  '🛹': ['skateboard', 'skating'],
  '🛼': ['roller', 'skate', 'rollerblade'],
  '🚏': ['bus', 'stop', 'transport'],
  '🛣️': ['motorway', 'highway', 'road'],
  '🛤️': ['railway', 'track', 'train'],
  '⛽': ['fuel', 'pump', 'gas', 'petrol'],
  '🚧': ['construction', 'warning', 'road'],
  '⚓': ['anchor', 'boat', 'ship'],
  '🛟': ['ring', 'buoy', 'life', 'float', 'swim'],
  '⛵': ['sailboat', 'boat', 'ship', 'sea'],
  '🚤': ['speedboat', 'fast', 'ship', 'sea'],
  '🛥️': ['motor', 'boat', 'ship', 'yacht'],
  '🛳️': ['passenger', 'ship', 'cruise', 'boat'],
  '⛴️': ['ferry', 'ship', 'boat', 'sea'],
  '🚢': ['ship', 'boat', 'cruise', 'passenger'],
  '✈️': ['plane', 'airplane', 'fly', 'flight'],
  '🛩️': ['plane', 'small', 'airplane'],
  '🛫': ['departure', 'plane', 'flight', 'takeoff'],
  '🛬': ['arrival', 'plane', 'flight', 'landing'],
  '🪂': ['parachute', 'fly', 'jump'],
  '💺': ['seat', 'chair', 'plane'],
  '🚁': ['helicopter', 'chopper', 'fly', 'air'],
  '🚟': ['suspension', 'railway', 'cable'],
  '🚠': ['mountain', 'cableway', 'gondola'],
  '🚡': ['aerial', 'tramway', 'cable', 'car'],
  '🛰️': ['satellite', 'orbit', 'space'],
  '🚀': ['rocket', 'launch', 'space', 'blastoff'],
  '🛸': ['ufo', 'flying', 'saucer', 'alien'],
  // Places
  '🎡': ['ferris', 'wheel', 'amusement'],
  '🎢': ['roller', 'coaster', 'fun', 'amusement'],
  '🎠': ['carousel', 'horse', 'amusement'],
  '🏗️': ['construction', 'crane', 'building'],
  '🌁': ['foggy', 'weather', 'tokyo', 'fog'],
  '🗼': ['tower', 'tokyo', 'landmark'],
  '🏢': ['office', 'building', 'business'],
  '🏬': ['department', 'store', 'shopping'],
  '🏣': ['post', 'office', 'japan', 'stamp'],
  '🏤': ['post', 'office', 'european'],
  '🏥': ['hospital', 'medical', 'doctor', 'clinic'],
  '🏦': ['bank', 'money', 'building'],
  '🏨': ['hotel', 'building', 'lodging'],
  '🏩': ['love', 'hotel', 'heart'],
  '💒': ['wedding', 'church', 'marriage'],
  '🏛️': ['classical', 'building', 'columns'],
  '⛪': ['church', 'christian', 'cross', 'religion'],
  '🕌': ['mosque', 'islam', 'religion'],
  '🕍': ['synagogue', 'judaism', 'jewish', 'religion'],
  '🛕': ['hindu', 'temple', 'religion'],
  '🕋': ['kaaba', 'mosque', 'islam', 'makkah'],
  '⛩️': ['shinto', 'shrine', 'japan', 'religion'],
  '🗾': ['japan', 'map', 'island'],
  '🎑': ['ceremony', 'scene', 'moon', 'japan'],
  '🏞️': ['national', 'park', 'nature', 'scenic'],
  '🌅': ['sunrise', 'landscape', 'horizon', 'morning'],
  '🌄': ['sunrise', 'mountains', 'over', 'mountain'],
  '🎇': ['fireworks', 'festival', 'celebration'],
  '🎆': ['fireworks', 'celebration', 'party'],
  '🌃': ['night', 'scene', 'building', 'city'],
  '🏙️': ['cityscape', 'city', 'buildings'],
  '🌉': ['bridge', 'night', 'tokyo', 'bay'],
  '🗺️': ['map', 'world', 'folded'],
  '🧭': ['compass', 'direction', 'navigation'],
  '🏔️': ['mountain', 'snow', 'peak'],
  '⛰️': ['mountain', 'climb'],
  '🌋': ['volcano', 'erupting', 'mountain', 'lava'],
  '🗻': ['fuji', 'mountain', 'japan'],
  '🏕️': ['camping', 'tent', 'outdoor'],
  '🏖️': ['beach', 'umbrella', 'sand', 'sun'],
  '🏜️': ['desert', 'camp', 'cactus'],
  '🏝️': ['desert', 'island', 'tropical'],
  '🏟️': ['stadium', 'sports', 'arena'],
  '🧱': ['brick', 'bricks', 'wall'],
  '🛖': ['hut', 'house', 'home', 'tropical'],
  '🏘️': ['houses', 'buildings'],
  '🏚️': ['house', 'derelict', 'abandoned'],
  '🏠': ['house', 'home', 'building'],
  '🏡': ['house', 'garden', 'home'],
  '🏪': ['convenience', 'store', 'shop'],
  '🏫': ['school', 'building', 'education'],
  '🏭': ['factory', 'building', 'industry'],
  '🏯': ['castle', 'japanese', 'building'],
  '🏰': ['castle', 'european', 'building'],
  // Activities
  '⚽': ['soccer', 'ball', 'football', 'sport'],
  '🏀': ['basketball', 'ball', 'sport'],
  '🏈': ['football', 'american', 'ball', 'sport'],
  '⚾': ['baseball', 'ball', 'sport'],
  '🥎': ['softball', 'ball', 'sport'],
  '🎾': ['tennis', 'ball', 'sport'],
  '🏐': ['volleyball', 'ball', 'sport'],
  '🏉': ['football', 'rugby', 'australian'],
  '🥏': ['flying', 'disc', 'frisbee'],
  '🎱': ['pool', '8 ball', 'billiards'],
  '🪀': ['yo-yo', 'yoyo', 'toy'],
  '🏓': ['ping', 'pong', 'table', 'tennis'],
  '🏸': ['badminton', 'sport'],
  '🏒': ['hockey', 'field', 'sport'],
  '🥍': ['lacrosse', 'sport', 'stick'],
  '🏑': ['hockey', 'field', 'sport'],
  '🥊': ['boxing', 'glove', 'sport'],
  '🥋': ['martial', 'arts', 'uniform'],
  '🎽': ['running', 'shirt', 'sport', 'athletic'],
  '🛷': ['sleigh', 'sled', 'winter'],
  '⛸️': ['ice', 'skate', 'winter'],
  '🥌': ['curling', 'stone', 'sport', 'winter'],
  '🎿': ['skis', 'winter', 'sport'],
  '⛷️': ['skier', 'snow', 'winter', 'sport'],
  '🏂': ['snowboarder', 'winter', 'sport'],
  '🏋️': ['weight', 'lifting', 'gym', 'sport'],
  '🤼': ['wrestling', 'sport'],
  '🤸': ['gymnastics', 'sport', 'flip'],
  '⛹️': ['ball', 'bouncing', 'sport'],
  '🤺': ['fencing', 'sport', 'sword'],
  '🏇': ['horse', 'racing', 'sport', 'jockey'],
  '🧘': ['person', 'meditation', 'yoga'],
  '🏄': ['surfing', 'wave', 'sport'],
  '🏊': ['swimming', 'pool', 'sport'],
  '🤽': ['water', 'polo', 'sport'],
  '🚣': ['rowing', 'boat', 'sport'],
  '🧗': ['climbing', 'rock', 'sport'],
  '🚵': ['mountain', 'biking', 'sport'],
  '🚴': ['biking', 'cycling', 'sport'],
  '🏆': ['trophy', 'award', 'winner', 'prize'],
  '🥇': ['medal', 'gold', 'first', 'winner'],
  '🥈': ['medal', 'silver', 'second'],
  '🥉': ['medal', 'bronze', 'third'],
  '🏅': ['medal', 'sports', 'award'],
  '🎖️': ['medal', 'military', 'award'],
  '🏵️': ['rosette', 'flower', 'award', 'ribbon'],
  '🎗️': ['reminder', 'ribbon', 'awareness'],
  '🎫': ['ticket', 'admission', 'event'],
  '🎟️': ['tickets', 'admission', 'entry'],
  '🎪': ['circus', 'tent', 'show'],
  '🤹': ['juggling', 'multitask', 'skill'],
  '🎭': ['theater', 'masks', 'drama', 'acting'],
  '🎨': ['art', 'painting', 'palette', 'painter'],
  '🎬': ['clapper', 'movie', 'film'],
  '🎤': ['microphone', 'karaoke', 'singer', 'sing'],
  '🎧': ['headphone', 'music', 'listen'],
  '🎼': ['score', 'music', 'sheet', 'notation'],
  '🎵': ['note', 'music'],
  '🎶': ['notes', 'music'],
  '🎷': ['sax', 'saxophone', 'music', 'jazz'],
  '🪗': ['accordion', 'music', 'instrument'],
  '🎸': ['guitar', 'music', 'rock', 'instrument'],
  '🎹': ['piano', 'music', 'keys', 'instrument'],
  '🎺': ['trumpet', 'music', 'brass', 'instrument'],
  '🎻': ['violin', 'music', 'strings', 'instrument'],
  '🪕': ['banjo', 'music', 'country', 'instrument'],
  '🥁': ['drum', 'music', 'percussion', 'instrument'],
  '🪘': ['long', 'drum', 'music'],
  '🎯': ['dart', 'bullseye', 'target', 'game'],
  '🎳': ['bowling', 'game', 'pin'],
  '🎮': ['game', 'controller', 'video game'],
  '🎰': ['slot', 'machine', 'gambling', 'casino'],
  '🧩': ['puzzle', 'piece', 'jigsaw', 'clue'],
  '🪄': ['magic', 'wand', 'wizard'],
  '🎲': ['dice', 'game', 'gambling'],
  '♟️': ['chess', 'pawn', 'game'],
  '🖼️': ['frame', 'picture', 'art', 'museum'],
  '🧵': ['thread', 'sewing', 'needle'],
  '🪡': ['sewing', 'needle', 'stitch'],
  '🧶': ['yarn', 'knitting', 'crochet'],
  '🪢': ['knot', 'rope', 'tie'],
  // Objects
  '💡': ['bulb', 'light', 'idea', 'bright', 'lamp'],
  '🔦': ['flashlight', 'torch', 'light'],
  '🕯️': ['candle', 'light', 'flame', 'wax'],
  '🪔': ['diya', 'lamp', 'light', 'diwali'],
  '💰': ['money', 'bag', 'dollar', 'cash'],
  '💴': ['yen', 'note', 'money', 'japanese'],
  '💵': ['dollar', 'note', 'money', 'usd'],
  '💶': ['euro', 'note', 'money'],
  '💷': ['pound', 'note', 'money', 'british'],
  '💸': ['money', 'wings', 'flying', 'cash'],
  '💳': ['card', 'credit', 'debit', 'money'],
  '🪙': ['coin', 'money', 'metal'],
  '💹': ['chart', 'increase', 'yen', 'market'],
  '📈': ['chart', 'increase', 'growth', 'trend'],
  '📉': ['chart', 'decrease', 'down', 'trend'],
  '📊': ['chart', 'columns', 'graph', 'data'],
  '💼': ['briefcase', 'work', 'business'],
  '🧳': ['luggage', 'suitcase', 'travel'],
  '📁': ['folder', 'file', 'directory'],
  '📂': ['folder', 'file', 'open', 'directory'],
  '🗂️': ['dividers', 'tabs', 'organizer'],
  '📋': ['clipboard', 'list', 'check'],
  '📌': ['pushpin', 'pin', 'thumbtack'],
  '📍': ['pushpin', 'round', 'location', 'pin'],
  '📎': ['paperclip', 'clip', 'attach'],
  '🖇️': ['paperclips', 'linked', 'clip'],
  '📏': ['ruler', 'straight', 'measure'],
  '📐': ['ruler', 'triangle', 'measure'],
  '✂️': ['scissors', 'cut'],
  '🗃️': ['file', 'box', 'card', 'index'],
  '🗄️': ['file', 'cabinet', 'filing'],
  '🗑️': ['wastebasket', 'trash', 'garbage'],
  '🔒': ['lock', 'secure', 'closed'],
  '🔓': ['unlock', 'open', 'unlocked'],
  '🔏': ['lock', 'private', 'pen'],
  '🔐': ['lock', 'security', 'key'],
  '🔑': ['key', 'password', 'open'],
  '🗝️': ['key', 'old', 'classic'],
  '🔨': ['hammer', 'tool'],
  '🪓': ['axe', 'tool', 'wood', 'chop'],
  '⛏️': ['pick', 'tool', 'mine'],
  '⚒️': ['hammer', 'pick', 'tool'],
  '🛠️': ['hammer', 'wrench', 'tool'],
  '🗡️': ['dagger', 'weapon', 'knife'],
  '⚔️': ['swords', 'crossed', 'weapon', 'battle'],
  '🔫': ['water', 'pistol', 'gun', 'toy'],
  '🛡️': ['shield', 'defense', 'protect'],
  '🪚': ['saw', 'tool', 'wood', 'cut'],
  '🔧': ['wrench', 'tool', 'spanner'],
  '🪛': ['screwdriver', 'tool'],
  '🔩': ['nut', 'bolt', 'screw'],
  '⚙️': ['gear', 'cog', 'settings'],
  '🗜️': ['clamp', 'tool', 'vise'],
  '🔗': ['link', 'chain', 'url'],
  '⛓️': ['chains', 'chain', 'lock'],
  '🪝': ['hook', 'fishing', 'catch'],
  '🧰': ['toolbox', 'tools', 'mechanic'],
  '🧲': ['magnet', 'attract', 'metal'],
  '🪜': ['ladder', 'climb'],
  '⚗️': ['alembic', 'distilling', 'chemistry'],
  '🔭': ['telescope', 'space', 'stars'],
  '🔬': ['microscope', 'lab', 'science'],
  '🩺': ['stethoscope', 'medical', 'doctor'],
  '🩻': ['x-ray', 'medical', 'bone', 'xray'],
  '💊': ['pill', 'medicine', 'drug', 'pharmacy'],
  '🩹': ['bandage', 'adhesive', 'medical'],
  '🩼': ['crutch', 'injury', 'disability'],
  '🪒': ['razor', 'shave', 'cutter'],
  '🧴': ['lotion', 'bottle', 'sunscreen'],
  '🧷': ['safety', 'pin', 'diaper'],
  '🧹': ['broom', 'sweep', 'clean'],
  '🧺': ['basket', 'laundry', 'picnic'],
  '🧻': ['toilet', 'paper', 'roll'],
  '🪣': ['bucket', 'pail', 'water'],
  '🧼': ['soap', 'bar', 'wash'],
  '🪥': ['toothbrush', 'brush', 'dental'],
  '🧽': ['sponge', 'absorb', 'clean'],
  '🧯': ['fire', 'extinguisher', 'put out'],
  '🛒': ['cart', 'shopping', 'trolley', 'buy'],
  '🚪': ['door', 'entrance'],
  '🪞': ['mirror', 'reflection', 'self'],
  '🪟': ['window', 'glass', 'opening'],
  '🛏️': ['bed', 'sleep', 'hotel'],
  '🛋️': ['couch', 'lounge', 'furniture', 'sofa'],
  '🚽': ['toilet', 'bathroom', 'loo'],
  '🪠': ['plunger', 'toilet', 'clog'],
  '🚿': ['shower', 'bathroom', 'water'],
  '🛁': ['bathtub', 'bathroom', 'soak'],
  '🪤': ['mouse', 'trap', 'cheese'],
  '🧸': ['teddy', 'bear', 'toy', 'plush'],
  '🪆': ['doll', 'nesting', 'russian'],
  '🛍️': ['shopping', 'bags', 'mall'],
  '📱': ['phone', 'mobile', 'cell', 'smartphone'],
  '💻': ['laptop', 'computer', 'notebook'],
  '🖥️': ['computer', 'desktop', 'monitor'],
  '🖨️': ['printer', 'print', 'paper'],
  '⌨️': ['keyboard', 'type'],
  '🖱️': ['computer', 'mouse', 'click'],
  '📷': ['camera', 'photo', 'picture'],
  '📸': ['camera', 'flash', 'photo'],
  '📹': ['camera', 'video', 'record'],
  '🎥': ['camera', 'movie', 'film'],
  '📽️': ['projector', 'movie', 'film'],
  '📞': ['receiver', 'phone', 'telephone'],
  '☎️': ['phone', 'telephone', 'call'],
  '📟': ['pager', 'old', 'retro'],
  '📠': ['fax', 'machine', 'retro'],
  '📺': ['tv', 'television', 'watch'],
  '📻': ['radio', 'music', 'broadcast', 'am fm'],
  '⏱️': ['stopwatch', 'timer', 'time'],
  '⏲️': ['timer', 'cook', 'time'],
  '⏰': ['alarm', 'clock', 'wake'],
  '🕰️': ['clock', 'mantelpiece', 'time'],
  '⌚': ['watch', 'time', 'wrist'],
  '📡': ['satellite', 'antenna', 'dish'],
  '🔋': ['battery', 'power', 'charge'],
  '🪫': ['battery', 'low', 'empty', 'dead'],
  '🔌': ['plug', 'electric', 'power'],
  // Symbols
  '❤️': ['heart', 'love', 'red'],
  '🧡': ['heart', 'orange', 'love'],
  '💛': ['heart', 'yellow', 'love'],
  '💚': ['heart', 'green', 'love'],
  '💙': ['heart', 'blue', 'love'],
  '💜': ['heart', 'purple', 'love'],
  '🖤': ['heart', 'black', 'grief'],
  '🤍': ['heart', 'white', 'pure'],
  '🤎': ['heart', 'brown'],
  '💔': ['heart', 'broken', 'breakup'],
  '❤️‍🔥': ['heart', 'fire', 'burning', 'love', 'passion'],
  '❤️‍🩹': ['heart', 'mending', 'recovering', 'hurt'],
  '❣️': ['heart', 'exclamation', 'love'],
  '💕': ['hearts', 'two', 'love'],
  '💞': ['hearts', 'revolving', 'love'],
  '💓': ['beating', 'heart', 'love'],
  '💗': ['growing', 'heart', 'love'],
  '💖': ['sparkling', 'heart', 'love'],
  '💘': ['arrow', 'heart', 'cupid', 'love'],
  '💝': ['heart', 'wrapped', 'gift', 'valentine'],
  '💟': ['decoration', 'heart', 'love'],
  '☮️': ['peace', 'symbol'],
  '✝️': ['cross', 'christian', 'religion'],
  '☪️': ['crescent', 'star', 'islam', 'muslim'],
  '🕉️': ['om', 'hindu', 'buddhist', 'sikh'],
  '✡️': ['star', 'david', 'jewish', 'judaism'],
  '🔯': ['star', 'six', 'pointed'],
  '🕎': ['menorah', 'hanukkah', 'jewish', 'candle'],
  '☯️': ['yin', 'yang', 'balance'],
  '☦️': ['orthodox', 'cross', 'christian'],
  '🛐': ['place', 'worship', 'religion'],
  '⛎': ['sagittarius', 'zodiac'],
  '♈': ['aries', 'zodiac'],
  '♉': ['taurus', 'zodiac'],
  '♊': ['gemini', 'zodiac'],
  '♋': ['cancer', 'zodiac'],
  '♌': ['leo', 'zodiac'],
  '♍': ['virgo', 'zodiac'],
  '♎': ['libra', 'zodiac'],
  '♏': ['scorpio', 'zodiac'],
  '♐': ['sagittarius', 'zodiac'],
  '♑': ['capricorn', 'zodiac'],
  '♒': ['aquarius', 'zodiac'],
  '♓': ['pisces', 'zodiac'],
  '🆔': ['id', 'identity'],
  '⚛️': ['atom', 'symbol', 'science'],
  '🉑': ['acceptable', 'ok', 'chinese'],
  '☢️': ['radioactive', 'danger'],
  '☣️': ['biohazard', 'danger', 'virus'],
  '📴': ['phone', 'off', 'mute'],
  '📳': ['phone', 'vibrate'],
  '🈶': ['charge', 'japanese', 'paid'],
  '🈚': ['free', 'charge', 'japanese'],
  '🈸': ['application', 'japanese'],
  '🈺': ['open', 'business', 'japanese'],
  '🈷️': ['monthly', 'japanese'],
  '✴️': ['star', 'mark', 'red'],
  '🆚': ['versus', 'vs', 'compete'],
  '💮': ['flower', 'white', 'japanese'],
  '🉐': ['bargain', 'cheap', 'good'],
  '㊙️': ['secret', 'top', 'classified'],
  '㊗️': ['congratulations', 'greetings', 'japanese'],
  '🈴': ['pass', 'japanese'],
  '🈵': ['not', 'empty', 'full'],
  '🈹': ['discount', 'sale', 'japanese'],
  '🈲': ['prohibited', 'japanese'],
  '🅰️': ['blood', 'type', 'a'],
  '🅱️': ['blood', 'type', 'b'],
  '🆎': ['blood', 'type', 'ab'],
  '🆑': ['click', 'here'],
  '🅾️': ['blood', 'type', 'o'],
  '🆘': ['help', 'sos', 'emergency'],
  '❌': ['x', 'mark', 'no', 'wrong', 'cancel'],
  '⭕': ['o', 'mark', 'yes', 'correct', 'ring'],
  '🛑': ['stop', 'sign', 'octagonal'],
  '⛔': ['entry', 'no', 'prohibited'],
  '📛': ['name', 'badge', 'label'],
  '🚫': ['prohibited', 'no', 'not allowed'],
  '💯': ['hundred', 'score', 'perfect', 'points'],
  '💢': ['anger', 'symbol', 'vein'],
  '♨️': ['hot', 'springs', 'steam'],
  '🚷': ['no', 'pedestrians', 'walk'],
  '🚯': ['no', 'littering', 'trash'],
  '🚳': ['no', 'bicycles', 'bike'],
  '🚱': ['non', 'drinking', 'water'],
  '🔞': ['no', 'under', 'eighteen', 'adult'],
  '📵': ['no', 'phones', 'mobile'],
  '🔕': ['bell', 'silent', 'no', 'volume'],
  '🔇': ['speaker', 'muted', 'silent', 'volume'],
  '🔈': ['speaker', 'volume', 'low'],
  '🔉': ['speaker', 'volume', 'medium'],
  '🔊': ['speaker', 'volume', 'loud', 'high'],
  '📢': ['loudspeaker', 'announcement', 'megaphone'],
  '📣': ['bullhorn', 'announcement', 'megaphone'],
  '🔔': ['bell', 'sound', 'notification'],
  '⚠️': ['warning', 'caution', 'danger'],
  '🚸': ['children', 'crossing', 'school'],
  '♻️': ['recycle', 'recycling', 'green', 'eco'],
  '✅': ['check', 'mark', 'yes', 'done', 'ballot'],
  '❎': ['mark', 'x', 'square', 'wrong'],
  '🆗': ['ok', 'good', 'yes'],
  '🆙': ['up', 'new', 'upgrade'],
  '🆒': ['cool', 'awesome'],
  '🆕': ['new', 'fresh', 'latest'],
  '🆓': ['free', 'no', 'cost'],
  '🔟': ['keycap', 'ten', 'number'],
  '🔠': ['input', 'latin', 'uppercase'],
  '🔡': ['input', 'latin', 'lowercase'],
  '🔢': ['input', 'numbers'],
  '🔣': ['input', 'symbols'],
  '🔤': ['input', 'letters'],
  '🚾': ['water', 'closet', 'toilet', 'restroom'],
  '⚕️': ['medical', 'symbol', 'asclepius'],
  '♾️': ['infinity', 'forever', 'endless'],
  '🔱': ['trident', 'symbol', 'poseidon'],
  '🔰': ['yellow', 'round', 'beginner', 'japanese'],
  '✔️': ['check', 'mark', 'yes', 'green'],
  '❓': ['question', 'mark', 'what', 'confused'],
  '❔': ['question', 'mark', 'white', 'puzzle'],
  '❕': ['exclamation', 'mark', 'white'],
  '❗': ['exclamation', 'mark', 'bang', 'important'],
  '〰️': ['wavy', 'dash', 'squiggly'],
  '💱': ['exchange', 'money', 'currency'],
  '💲': ['heavy', 'dollar', 'sign', 'money'],
  '➕': ['plus', 'math', 'add'],
  '➖': ['minus', 'math', 'subtract'],
  '➗': ['divide', 'math', 'division'],
  '✖️': ['multiply', 'math', 'times'],
  '🟰': ['equals', 'math', 'double', 'sign'],
  '‼️': ['exclamation', 'double'],
  '⁉️': ['exclamation', 'question', 'what'],
  '🔅': ['signal', 'low', 'brightness'],
  '🔆': ['signal', 'high', 'brightness'],
  '〽️': ['part', 'alternation', 'mark', 'japanese'],
  '⚜️': ['fleur', 'lis', 'ornament'],
  '🔷': ['diamond', 'blue', 'large'],
  '🔶': ['diamond', 'orange', 'large'],
  '🔹': ['diamond', 'blue', 'small'],
  '🔸': ['diamond', 'orange', 'small'],
  '🔺': ['triangle', 'pointing', 'up', 'red'],
  '🔻': ['triangle', 'pointing', 'down', 'red'],
  '💠': ['diamond', 'dot', 'blue'],
  '🔘': ['button', 'radio', 'circle'],
  '🔳': ['button', 'square', 'white'],
  '🔲': ['button', 'square', 'black'],
  // Flags
  '🏁': ['checkered', 'flag', 'racing', 'finish'],
  '🚩': ['flag', 'triangular', 'mark', 'red'],
  '🎌': ['flags', 'crossed', 'japanese'],
  '🏴': ['flag', 'black'],
  '🏳️': ['flag', 'white'],
  '🏳️‍🌈': ['flag', 'rainbow', 'pride', 'lgbt'],
  '🏳️‍⚧️': ['flag', 'trans', 'transgender'],
  '🏴‍☠️': ['flag', 'pirate', 'skull'],
};

/**
 * Check whether an emoji matches the given search query (case-insensitive).
 */
function emojiMatches(emoji: string, query: string): boolean {
  const tags = EMOJI_TAGS[emoji];
  if (tags?.some(tag => tag.includes(query))) return true;
  // Also match against section label
  const section = EMOJI_SECTIONS.find(sec => sec.emojis.includes(emoji));
  if (section?.label.toLowerCase().includes(query)) return true;
  return false;
}

interface EmojiPickerProps {
  value: string;
  onChange: (emoji: string) => void;
}

export const EmojiPicker: React.FC<EmojiPickerProps> = ({ value, onChange }) => {
  const [open, setOpen] = useState(false);
  const [activeSection, setActiveSection] = useState(0);
  const [search, setSearch] = useState('');
  const popoverRef = useRef<HTMLDivElement>(null);
  const sectionRefs = useRef<(HTMLDivElement | null)[]>([]);
  const gridRef = useRef<HTMLDivElement>(null);

  // Close on outside click
  useEffect(() => {
    if (!open) return;
    const handler = (e: MouseEvent) => {
      if (popoverRef.current && !popoverRef.current.contains(e.target as Node)) {
        setOpen(false);
        setSearch('');
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [open]);

  const handleSelect = (emoji: string) => {
    onChange(emoji);
    setOpen(false);
    setSearch('');
  };

  const scrollToSection = (index: number) => {
    setActiveSection(index);
    sectionRefs.current[index]?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  };

  const filteredSections = search.trim()
    ? [{
        label: 'Search Results',
        emoji: '🔍',
        emojis: EMOJI_SECTIONS.flatMap(s => s.emojis).filter(emoji => {
          // Literal emoji paste still works
          if (emoji.includes(search.trim())) return true;
          return emojiMatches(emoji, search.trim().toLowerCase());
        }),
      }]
    : EMOJI_SECTIONS;

  return (
    <div className="relative" ref={popoverRef}>
      {/* Trigger button */}
      <button
        type="button"
        onClick={() => setOpen(v => !v)}
        className="flex items-center gap-2 w-full border border-input bg-background text-foreground p-2 rounded-md focus:ring-2 focus:ring-ring outline-none hover:bg-secondary/50 transition-colors"
      >
        <span className="text-xl leading-none">{value}</span>
        <span className="text-sm text-muted-foreground flex-1 text-left">Pick emoji</span>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" className="w-4 h-4 text-muted-foreground">
          <path fillRule="evenodd" d="M5.22 8.22a.75.75 0 0 1 1.06 0L10 11.94l3.72-3.72a.75.75 0 1 1 1.06 1.06l-4.25 4.25a.75.75 0 0 1-1.06 0L5.22 9.28a.75.75 0 0 1 0-1.06Z" clipRule="evenodd" />
        </svg>
      </button>

      {/* Popover */}
      {open && (
        <div className="absolute z-50 mt-1 left-0 w-80 bg-card border border-border rounded-xl shadow-2xl flex flex-col overflow-hidden"
          style={{ maxHeight: '380px' }}>

          {/* Search bar */}
          <div className="p-2 border-b border-border">
            <input
              autoFocus
              type="text"
              placeholder="Search emoji…"
              value={search}
              onChange={e => setSearch(e.target.value)}
              className="w-full bg-background text-foreground text-sm border border-input rounded-md px-3 py-1.5 outline-none focus:ring-2 focus:ring-ring"
            />
          </div>

          {/* Section tab bar */}
          {!search && (
            <div className="flex overflow-x-auto border-b border-border bg-card scrollbar-hide">
              {EMOJI_SECTIONS.map((section, i) => (
                <button
                  key={section.label}
                  type="button"
                  title={section.label}
                  onClick={() => scrollToSection(i)}
                  className={`flex-shrink-0 px-2 py-1.5 text-lg transition-colors hover:bg-secondary/60 ${activeSection === i ? 'border-b-2 border-primary bg-secondary/40' : ''}`}
                >
                  {section.emoji}
                </button>
              ))}
            </div>
          )}

          {/* Emoji grid */}
          <div ref={gridRef} className="overflow-y-auto flex-1 p-2 space-y-3">
            {filteredSections.map((section, si) => (
              <div key={section.label} ref={el => { sectionRefs.current[si] = el; }}>
                <p className="text-[10px] font-semibold uppercase tracking-widest text-muted-foreground mb-1 px-1">
                  {section.label}
                </p>
                <div className="grid grid-cols-8 gap-0.5">
                  {section.emojis.map(emoji => (
                    <button
                      key={emoji}
                      type="button"
                      onClick={() => handleSelect(emoji)}
                      title={emoji}
                      className={`text-xl p-1 rounded-md hover:bg-secondary transition-colors leading-none ${value === emoji ? 'bg-primary/20 ring-1 ring-primary' : ''}`}
                    >
                      {emoji}
                    </button>
                  ))}
                </div>
              </div>
            ))}
            {filteredSections[0]?.emojis.length === 0 && (
              <p className="text-sm text-muted-foreground text-center py-6">No emoji found</p>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
