spring.application.name=budget-tracker

# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/budget_tracker
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Jackson configuration
spring.jackson.serialization.write-dates-as-timestamps=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Security flag
app.security.enabled=true

# Data Seeder
app.data-seeder.enabled=false

# JWT Configuration
# In production, app.security.jwt.secret should be a long base64 string
app.security.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.security.jwt.expiration-ms=86400000